[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
rayon = "1.5.1"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.75"
typetag = "0.1.2"

[profile.release]
debug = true
